export const GET_ALL_FLIGHTS = 'GET_ALL_FLIGHTS';
export const SET_ALL_FLIGHTS = 'SET_ALL_FLIGHTS';
export const FETCH_FLIGHTS_FAILED = 'FETCH_FLIGHTS_FAILED';
export const ADD_FLIGHTS = 'ADD_FLIGHTS';
export const ADD_FLIGHTS_SUCCESS = 'ADD_FLIGHTS_SUCCESS';
export const ADD_FLIGHTS_FAILED = 'ADD_FLIGHTS_FAILED';